-- CONSULTAR PENSUM
BEGIN
	consultarpensum(1);
END;

-- CONSULTAR ESTUDIANTE
BEGIN
	consultarestudiante(202000166);
END;

-- CONSULTAR DOCENTE
BEGIN
	consultardocente(22);
END;

-- CONSULTAR ESTUDIANTES ASIGNADOS
BEGIN
	CONSULTARESTUDIENTESASIGNADOS(512, '2S', 2023, 'P');
END;
-- CONSULTAR ESTUDIANTES APROBADOS
BEGIN
	CONSULTARESTUDIENTESAPROBADOS(512, '2S', 2023, 'P');
END;

-- CONSULTAR ESTUDIANTES DESASIGNADOS 
BEGIN
	CONSULTARESTUDIENTESDESASIGNADOS(512, '2S', 2023, 'P');
END;